""" This module generates notes for a midi file using the
    trained neural network """
import pickle
import glob
import numpy as np

from music21 import instrument, note, stream, chord, duration
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.layers import Activation

import midi_util
import network


def generate():
    """ Generate a piano midi file """
    # parse midi songs to notes file
    midi_path = "midi_songs/*.mid"
    data_path = "midi_input/data"

    if glob.glob(data_path):
        data = midi_util.load_data(data_path)
    else:
        data = midi_util.parse_midi(midi_path, data_path)

    sequence_length = 32

    pitches = midi_util.PitchTable
    pitch_size = len(pitches)

    duration_min = midi_util.DurationMin
    duration_max = midi_util.DurationMax
    duration_size = int(duration_max // duration_min)

    print(pitches)

    normalized_input = prepare_sequences(data, sequence_length, pitches, duration_min, duration_max)

    model = network.create(normalized_input, pitch_size, duration_size, weights_path="weights/weights-improvement-19-0.1743-bigger.hdf5")

    prediction_output = generate_notes(model, sequence_length, pitches, duration_min, duration_max)
    create_midi(prediction_output)

def prepare_sequences(data, sequence_length, pitches, duration_min, duration_max):
    """ Prepare the sequences used by the Neural Network """
    n_vocab = len(pitches)
    print(n_vocab)

    # create a dictionary to map pitches to integers
    ps_to_int = dict((pitch, number) for number, pitch in enumerate(pitches))

    network_input = []

    for notes in data:
        for i in range(0, len(notes) - sequence_length, 1):
            sequence_in = notes[i:i + sequence_length]
            network_input.append([np.array([ps_to_int[note[0]], (note[1] // duration_min - 1)]) for note in sequence_in])

    n_patterns = len(network_input)

    # reshape the input into a format compatible with LSTM layers
    normalized_input = np.reshape(network_input, (n_patterns, sequence_length, 2))
    # normalize input
    normalized_input[:,:,0] = normalized_input[:,:,0] / float(n_vocab)
    normalized_input[:,:,1] = normalized_input[:,:,1] / float(duration_max // duration_min)

    return normalized_input

def generate_notes(model, sequence_length, pitches, duration_min, duration_max):
    """ Generate notes from the neural network based on a sequence of notes """
    # pick a random sequence from the input as a starting point for the prediction

    int_to_ps = dict((number, note) for number, note in enumerate(pitches))

    pitch_size = len(pitches)
    duration_size = int(duration_max // duration_min)

    random_seq_pitch = np.random.randint(pitch_size, size=sequence_length)
    random_seq_duraion = np.random.randint(duration_size, size=sequence_length)

    pattern = np.vstack((random_seq_pitch, random_seq_duraion)).T

    prediction_output = []

    # generate 500 notes
    for note_index in range(500):
        prediction_input = np.reshape(pattern, (1, pattern.shape[0], pattern.shape[1]))
        prediction_input = prediction_input / float(pitch_size)

        prediction = model.predict(prediction_input, verbose=0)
        
        ps_index = np.argmax(prediction[0])
        dt_index = np.argmax(prediction[1])

        predict_pitch = int_to_ps[ps_index]
        predict_duration = (dt_index + 1) * duration_min

        prediction_output.append((predict_pitch, predict_duration))

        pattern[0:-1] = pattern[1:len(pattern)]
        pattern[-1] = np.array([ps_index, dt_index])

        # random modify the pattern to prevent loop in weird melody
        pattern_index = np.random.randint(len(pattern) - 1)
        pattern[pattern_index][0] = np.random.randint(pitch_size)

    return prediction_output

def create_midi(prediction_output):
    """ convert the output from the prediction to notes and create a midi file
        from the notes """
    offset = 0
    output_notes = []

    # create note and chord objects based on the values generated by the model
    for (ps, dt) in prediction_output:

        if ps != 0:
            new_note = note.Note(ps)
            new_note.offset = offset
            new_note.duration = duration.Duration(quarterLength=dt)
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)
        else:
            new_note = note.Rest()
            new_note.offset = offset
            new_note.duration = duration.Duration(quarterLength=dt)
            new_note.storedInstrument = instrument.Piano()
            output_notes.append(new_note)

        # increase offset each iteration so that notes do not stack
        offset += dt

    midi_stream = stream.Stream(output_notes)
    midi_stream.write('midi', fp='test_output.mid')

if __name__ == '__main__':
    generate()
